<?php

/**
 * @file
 * API Extension for using Leaflet with GeoJSON that currently just allows to add a bbox strategy.
 */

function leaflet_geojson_add_bbox_support($url) {
  // Add bounding box javascript.
  drupal_add_js(
    drupal_get_path('module', 'leaflet_geojson') . '/leaflet.bbox.js',
    // Add our script after leaflet.drupal.js.
    array('weight' => 5)
  );
  // Add custom settings.
  $settings = array(
    'url' => $url,
  );
  drupal_add_js(array('leafletBBox' => $settings), 'setting');
}
